### ISSUE TITLE
unnecessary Sentry errors: Non-Error exception

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#701]
We started getting a lot of these sentry errors last week, but they don't seem to be meaningful. Can we stop them somehow in the app? Or should we just filter them out at Sentry?

Error: Non-Error exception captured with keys: detail, errorStatusCode

https://sentry.io/mit-office-of-digital-learning/odl-video-service/issues/677341116/

```
Error: Non-Error exception captured with keys: detail, errorStatusCode
  at captureException (./node_modules/raven-js/src/raven.js:500:1)
  at o._promiseRejectionHandler (./node_modules/raven-js/src/raven.js:431:1)

Non-Error exception captured with keys: detail, errorStatusCode
```

**Comment by pdpinch** [comment]
Sentry issue: [ODL-VIDEO-SERVICE-BT](https://sentry.io/mit-office-of-digital-learning/odl-video-service/issues/677361072/)

**Comment by pdpinch** [comment]
The sentry issues are no longer available.
